# Generated by Django 5.1.4 on 2025-02-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
