# Generated by Django 5.1.4 on 2025-02-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='availability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
