# Generated by Django 5.1.4 on 2025-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0002_paymentdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
