# Generated by Django 5.1.4 on 2025-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0002_alter_paymentdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettrend',
            name='market_trends',
            field=models.JSONField(default=list),
        ),
    ]
