# Generated by Django 5.1.4 on 2025-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0003_alter_paymentdetails_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='co_operativeID',
        ),
    ]
