# Generated by Django 5.1.4 on 2025-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0003_alter_crop_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='availability',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]
