# Generated by Django 5.1.4 on 2025-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0004_remove_markettrend_market_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farm_Image',
            field=models.ImageField(blank=True, null=True, upload_to='farmImages/'),
        ),
    ]
