# Generated by Django 5.1.4 on 2025-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0004_remove_farmer_co_operativeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='contact',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='contact',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
