# Generated by Django 5.1.4 on 2025-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0007_alter_profile_farm_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='farm_Image',
            field=models.ImageField(blank=True, null=True, upload_to='AgriLink_Images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AgriLink_Images'),
        ),
    ]
