# Generated by Django 5.1.4 on 2025-03-04 12:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0011_alter_profile_farm_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
