# Generated by Django 5.1.4 on 2025-03-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0013_alter_ordercrop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
