# Generated by Django 5.1.4 on 2025-03-22 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0014_emailintiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailintiation',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
