# Generated by Django 5.1.4 on 2025-03-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0015_emailintiation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailintiation',
            name='farm_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailintiation',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
