# Generated by Django 5.1.4 on 2025-03-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0016_emailintiation_farm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercrop',
            name='crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Agri_Link.crop'),
            preserve_default=False,
        ),
    ]
