# Generated by Django 5.1.4 on 2025-03-26 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0017_ordercrop_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercrop',
            name='buyer_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_order', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercrop',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_crop', to='Agri_Link.crop'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_farmer',
            field=models.BooleanField(db_index=True),
        ),
    ]
