# Generated by Django 5.1.4 on 2025-03-26 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Link', '0018_ordercrop_buyer_id_alter_ordercrop_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercrop',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
